return {
	"ThePrimeagen/harpoon",
	config = function()
		local ui = require("harpoon.ui")
		local mark = require("harpoon.mark")

		-- vim.keymap.set("n", "<C-a>", mark.add_file, { desc = "Add file to Harpoon" })
		vim.keymap.set("n", "<leader>ha", mark.add_file, { desc = "Add file to Harpoon" })
		vim.keymap.set("n", "<leader>hr", mark.rm_file, { desc = "Remove file from Harpoon" })
		vim.keymap.set("n", "<leader>he", ui.toggle_quick_menu, { desc = "Toggle Harpoon UI" })
		vim.keymap.set("n", "<leader>1", function()
			ui.nav_file(1)
		end, { desc = "Go to Harpoon 1" })
		vim.keymap.set("n", "<leader>2", function()
			ui.nav_file(2)
		end, { desc = "Go to Harpoon 2" })
		vim.keymap.set("n", "<leader>3", function()
			ui.nav_file(3)
		end, { desc = "Go to Harpoon 3" })

		-- 		vim.keymap.set("n", "<leader>a", mark.add_file, { desc = "Add file to Harpoon" })
		-- 		vim.keymap.set("n", "<C-e>", ui.toggle_quick_menu, { desc = "Toggle Harpoon UI" })
		-- 		vim.keymap.set("n", "<C-h>1", function()
		-- 			ui.nav_file(1)
		-- 		end, { desc = "Go to Harpoon 1" })
		-- 		vim.keymap.set("n", "<C-h>2", function()
		-- 			ui.nav_file(2)
		-- 		end, { desc = "Go to Harpoon 2" })
		-- 		vim.keymap.set("n", "<C-h>3", function()
		-- 			ui.nav_file(3)
		-- 		end, { desc = "Go to Harpoon 3" })

		-- vim.keymap.set("n", "<leader>a", mark.add_file)
		-- vim.keymap.set("n", "<C-e>", ui.toggle_quick_menu)

		-- vim.keymap.set("n", "<C-h>", function()
		-- 	ui.nav_file(1)
		-- end)
		-- vim.keymap.set("n", "<C-t>", function()
		-- 	ui.nav_file(2)
		-- end)
		-- vim.keymap.set("n", "<C-n>", function()
		-- 	ui.nav_file(3)
		-- end)
		-- vim.keymap.set("n", "<C-s>", function()
		-- 	ui.nav_file(4)
		-- end)
	end,
}

-- local mark = require("harpoon.mark")
-- local ui = require("harpoon.ui")
--
-- vim.keymap.set("n", "<leader>a", mark.add_file)
-- vim.keymap.set("n", "<C-e>", ui.toggle_quick_menu)
--
-- vim.keymap.set("n", "<C-h>", function() ui.nav_file(1) end)
-- vim.keymap.set("n", "<C-t>", function() ui.nav_file(2) end)
-- vim.keymap.set("n", "<C-n>", function() ui.nav_file(3) end)
-- vim.keymap.set("n", "<C-s>", function() ui.nav_file(4) end)
